# Generated by Django 4.2.11 on 2024-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_posts_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
